// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiai0lM3gxvaaTyMAKMkVbsmURcOTdVKc',
    appId: '1:284280385996:web:c1238f2cb7f8ff54d56d69',
    messagingSenderId: '284280385996',
    projectId: 'todo-app-ddd0b',
    authDomain: 'todo-app-ddd0b.firebaseapp.com',
    storageBucket: 'todo-app-ddd0b.firebasestorage.app',
    measurementId: 'G-PPX5J95MV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxOv6fEFsAVreH3pp4yLBVKJ9_CWtOXs',
    appId: '1:284280385996:android:aad4111ba7db2795d56d69',
    messagingSenderId: '284280385996',
    projectId: 'todo-app-ddd0b',
    storageBucket: 'todo-app-ddd0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOBxylJP--fwaV5Gy8uNhL4xxyD1hkuAc',
    appId: '1:284280385996:ios:7015478e4cb696dbd56d69',
    messagingSenderId: '284280385996',
    projectId: 'todo-app-ddd0b',
    storageBucket: 'todo-app-ddd0b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOBxylJP--fwaV5Gy8uNhL4xxyD1hkuAc',
    appId: '1:284280385996:ios:7015478e4cb696dbd56d69',
    messagingSenderId: '284280385996',
    projectId: 'todo-app-ddd0b',
    storageBucket: 'todo-app-ddd0b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiai0lM3gxvaaTyMAKMkVbsmURcOTdVKc',
    appId: '1:284280385996:web:30119ff98b761aadd56d69',
    messagingSenderId: '284280385996',
    projectId: 'todo-app-ddd0b',
    authDomain: 'todo-app-ddd0b.firebaseapp.com',
    storageBucket: 'todo-app-ddd0b.firebasestorage.app',
    measurementId: 'G-J6DP1TX4M5',
  );
}
